### ISSUE TITLE
Failed to resolve import 

### ISSUE THREAD

**Issue by djeetee** [shaack/cm-pgn#16]
Hi Stefan, I updated cm-pgn to 2.3.4 from 2.3.1 and I'm getting the following error:

`Failed to resolve import "../../lib/chess.mjs/Chess.js" from "node_modules/cm-pgn/src/cm-pgn/History.js?v=e7e4b3e6". Does the file exist?`

This looks like an internal reference error within cm-pgn.

Any thoughts on what's going on?

Having just gone through upgrading cm-chessboard I think this is related to this path structure `/cm-pgn/src/cm-pgn/` in the above as I see you have corrected a similar this structure in cm-chessboard.

thanks

**Comment by shaack** [comment]
I switched to "importmap" in my projects. The path "../../lib" should not exist anymore in the code. Version 2.3.4 my be broken, please try to update to the current version 3.3.0.

**Comment by djeetee** [comment]
the upgrade fixed it. thank you.
