### ISSUE TITLE
How to run unit tests?

### ISSUE THREAD

**Issue by jackstenglein** [shaack/cm-pgn#18]
I've converted this package to Typescript in my fork, but I'm not sure how to run the unit tests to check it. The `npm test` script seems to suggest that I should just open `test/index.html`, but when I do that, I see errors like:

`
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///Users/jackstenglein/Documents/projects/cm-pgn/test/PgnList.test.js. (Reason: CORS request not http).
`

Also, if I can verify that the tests still pass, would you be interested in a PR for the Typescript conversion?

**Comment by jackstenglein** [comment]
Closing this as I decided to just migrate the existing tests over to jest and use that to run them.

**Comment by shaack** [comment]
Typescript is not something I will use, it makes everything more complicated. But do what you feel to.
