### ISSUE TITLE
Unable to import in typescript project

### ISSUE THREAD

**Issue by MarkShurmer** [shaack/cm-pgn#23]
I've been trying to use your pgn parser from typescript, as it looks very good for parsing PGNs

I have a typescript project set up , using next.js and vitest

I am using ESM modules, so that shouldn't be a problem.

The error I get is:
`Error: Failed to resolve entry for package "cm-pgn". The package may have incorrect main/module/exports specified in its package.json.`

I wonder if it is due to the main section of your package.json being thus:
` "main": "src/cm-pgn/Pgn.js"`
When maybe it should be 
` "main": "src/Pgn.js"`

I'm happy to create a PR

**Comment by shaack** [comment]
Yes, this is wrong in the package.json. Would be great if you create a PR which makes it working with TypeScript. 👍
