### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jvsteiner** [shaack/cm-pgn#6]
It would be nice to have some basic installation/usage documentation, including information how do you use it in the browser.

**Comment by shaack** [comment]
Yes, cm-pgn is a weekend project and therefore the documentation is not very good.
You may take a look in the tests: https://github.com/shaack/cm-pgn/tree/master/test there are some examples of the usage.

And cm-pgn is used in some of my other projects, see 
- https://github.com/shaack/cm-chess
- https://github.com/shaack/cm-fen-editor (uses cm-chess, which is mainly chess.js + cm-pgn in ES6)
- https://github.com/shaack/chess-console (uses cm-chess, which is mainly chess.js + cm-pgn in ES6)
