### ISSUE TITLE
Uncaught peg$SyntaxError

### ISSUE THREAD

**Issue by ExtremeCoolDude** [shaack/cm-pgn#8]
Hello, I'm getting this error message : 

`Uncaught peg$SyntaxError {message: "Expected " ", "*", "0-1", "0:1", "1-0", "1/2-1/2",…], [a-h], end of input, or integer but "[" found.", expected: Array(44), found: "[", location: {…}, name: "SyntaxError", …}`

Code: 

```
<script type="module">
  import {Pgn} from "/Pgn.js";
  const pgnvv = new Pgn(PGN);
console.log(pgnvv.history());
</script>
```

PGN:

```
[Event "?"]
[Site "?"]
[Date "????.??.??"]
[Round "?"]
[White "?"]
[Black "?"]
[Result "*"]
[FEN "r3kb1r/pbq2ppp/2p2n2/1pn1pP2/4P1P1/2NB1Q2/PPPBN2P/R3K2R w KQkq - 0 1"]
[Setup "1"]

1. a4 { [%csl Rh1,Ra8,Gf6,Gc5,Gc3,Gb5,Yb4,Yb7,Yc6,Ra1,Rg2,Rf3,Re4,Rd5][%cal
Gf6e4,Gc5e4,Gc3d1,Gd1f2,Rb7e4,Re4h1,Rg4g5,Rf6d7]}  ( 1. g5)1... b4 2. Nd1 Nfxe4
3. Bxe4 Nxe4 4. Qxe4 c5 5. Qc4 Bxh1 6. Bxb4 Be7 7. Ne3 O-O 8. O-O-O Bf3 9. Nd5
Qb7 10. f6 Bxd5 11. Qxd5 Qxd5 12. Rxd5 gxf6 13. Bxc5 Rfd8 14. Rxd8+ Bxd8 15. b4
h5 16. h3 hxg4 17. hxg4 Kg7 18. Ng3 Bb6 19. Be7 Kg6 20. c4 Bf2 21. Nf5 Kg5 22.
Nd6 Kxg4 23. c5 Kf3 24. c6 e4 25. c7 Bd4 26. Nb5 Be5 27. Bd6 e3 28. Bxe5 fxe5
29. Nd6 Kf2  *

```
When I strip all the headers manually  I get :  

`IllegalMoveException {fen: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1", notation: "g5", toString: ƒ}
`

But g5 is a variation, not an illegal move.

**Comment by shaack** [comment]
I suspect the [ in the comment is the problem because no [ or ] are expected outside the header.

**Comment by shaack** [comment]
The PGN header tags are case sensitiv, you must use `[SetUp "1"]` not `[Setup "1"]`. 

See: http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm
8.1: Tag pair section: "Tag names, like all symbols, are case sensitive."

**Comment by ExtremeCoolDude** [comment]
Thanks a lot for the reply. test.html shows that pgn should pass. Unfortunately, I can't get it to work.  I'm pretty new to coding and was wondering if you have any advice if other factors then the code itself can cause this behaviour. I'm trying to use this pgn handler to handle the pgn in Anki software : 
https://github.com/ExtremeCoolDude/Anki-Chess-2.0

error: 


![image](https://user-images.githubusercontent.com/50034073/109363758-6bec6400-78b5-11eb-9f55-e6a5d732c1e3.png)


code : 

![image](https://user-images.githubusercontent.com/50034073/109363793-7d357080-78b5-11eb-96ba-a6ed70f88fe0.png)

PGN : 

![image](https://user-images.githubusercontent.com/50034073/109361528-2cbc1400-78b1-11eb-98e6-87686079d80c.png)

**Comment by ExtremeCoolDude** [comment]
Update : It shows the same error with the example from github's readme.md : 
   ```
 import {Pgn} from "./src/cm-pgn/Pgn.js";
    // parse pgn
    const pgn = new Pgn(`[Site "Berlin"]
                         [Date "1989.07.02"]
                         [White "Haack, Stefan"]
                         [Black "Maier, Karsten"]
                         1. e2-e4 e7e5 (e6) 2. Nf3 $1 {Great move!} Nc6`);
```

So it's not related to  pgn. Not sure what's causing this. I'm using a live server on chrome so it shouldn't be affected by chrome's coor policy. 


  ```
  import {Pgn} from "./src/cm-pgn/Pgn.js";
    // parse pgn
    const pgn = new Pgn(`[Site "Berlin"]
                         [Date "1989.07.02"]
                         [White "Haack, Stefan"]
                         [Black "Maier, Karsten"]
                         1. e2-e4 e7e5 (e6) 2. Nf3 $1 {Great move!} Nc6`);

```

**Comment by ExtremeCoolDude** [comment]
Please forgive me if I'm missing something simple and being stupid but none of the pgn  which has at least a single header on test folder pass through the parser, simple san passes though.

![image](https://user-images.githubusercontent.com/50034073/109379414-45065000-78fe-11eb-96ce-e252d9cfb8de.png)

**Comment by shaack** [comment]
Oh, sorry, there have been failures in the README.md.
Correct is:

```[Site "Berlin"]
[Date "1989.07.02"]
[White "Haack, Stefan"]
[Black "Maier, Karsten"]

1. e4 e5 (e6) 2. Nf3 $1 {Great move!} Nc6 *
```

Some rules:

- There must be a blank newline after the header section
- Every Header field must end with a newline
and
- The (online) parser only parses only the history part, without the header and the history part must have no newlines

putting this in https://pegjs.org/online
```1. a4 { [%csl Rh1,Ra8,Gf6,Gc5,Gc3,Gb5,Yb4,Yb7,Yc6,Ra1,Rg2,Rf3,Re4,Rd5][%cal Gf6e4,Gc5e4,Gc3d1,Gd1f2,Rb7e4,Re4h1,Rg4g5,Rf6d7]}  ( 1. g5)1... b4 2. Nd1 Nfxe4 3. Bxe4 Nxe4 4. Qxe4 c5 5. Qc4 Bxh1 6. Bxb4 Be7 7. Ne3 O-O 8. O-O-O Bf3 9. Nd5 Qb7 10. f6 Bxd5 11. Qxd5 Qxd5 12. Rxd5 gxf6 13. Bxc5 Rfd8 14. Rxd8+ Bxd8 15. b4 h5 16. h3 hxg4 17. hxg4 Kg7 18. Ng3 Bb6 19. Be7 Kg6 20. c4 Bf2 21. Nf5 Kg5 22. Nd6 Kxg4 23. c5 Kf3 24. c6 e4 25. c7 Bd4 26. Nb5 Be5 27. Bd6 e3 28. Bxe5 fxe5 29. Nd6 Kf2  *```

will work:
![Bildschirmfoto 2021-02-27 um 09 40 04](https://user-images.githubusercontent.com/832120/109382273-d1554a80-78df-11eb-82f3-bfb59e302c24.png)

If you have further questions, just ask.

**Comment by ExtremeCoolDude** [comment]
Thanks a lot!

A few \n's were driving me crazy! :)

I have another question, can we just do `load_pgn() on ChessJs() ` since chess.js accepts FEN as a parameter, we could just do history() on ChessJs and that wouldn't be illegal if PGN had no FEN included inside it. 

Also on Anki since it cannot search for extra module js files, do you have any advice to bundle chess-cm into a single file ? I tried babel+browserify but keeping getting reference error on Chess() is not defined.

**Comment by shaack** [comment]
You mean "cm-chess"? https://github.com/shaack/cm-chess Yes, I have a problem with cm-chess, because it depends on chess.js https://github.com/jhlywa/chess.js, but chess.js in not shipped as an ES6 module. Therefore chess.js must be included separately via HTML, because it is not (easily) possible, to include non modules with a relative path into a module. One solution could be, to include the source of chess.js into cm-chess, but I have not done this so far.

**Comment by ExtremeCoolDude** [comment]
Yup, cm-chess! chess.js currently doesn't play well with variations and it's causing problems during pgn rendering.  Would this work though : Include minified chess.js inside the same html file as the entire bundled cm-chess ? Thanks a lot for your thoughts on this.

**Comment by shaack** [comment]
Yes, this should work.

**Comment by shaack** [comment]
Okay, with https://github.com/shaack/cm-pgn/commit/e31edbc2cd179ec06215b4cded2dc8bd7fda14a2 I created chess.mjs, and ES6 version of chess.js and it should work now, without including chess.js.

**Comment by ExtremeCoolDude** [comment]
Thanks a lot!

I've been tinkering with another library in the meantime : https://github.com/kevinludwig/pgn-parser
which has prebuilt js file to be inserted into <script>  made via webpack, which is working good so far on Anki! but has only parser, so move() is still needed to pass to chess.js. With cm-chess, I can do load_pgn() and don't need to handle array of moves manually. Hopefully I'll be able to output single js based on the same webpack config.

 The grammar file is tremedously better on @kevinludwig's repo though.  Setup with lower case u works and \n is not required., in case you want to change the source of grammar file.  Thanks again!

**Comment by shaack** [comment]
Thats interesting, thanks for the hint, I will take a look at the other grammar file.
